name = "TaxiTrips"
uuid = "4fb8f981-1137-425f-b422-4ea7a42de3a5"
version = "0.1.0"
authors = ["eeff < 33566201+eeff@users.noreply.github.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[sources]
Bench = {path = "../Bench"}

[compat]
CSV = "0.10.14"
Statistics = "1.11.1"
StructArrays = "0.6.18"
julia = "1.12"

[extras]
Bench = "517df1bc-ee24-4b58-84e4-955ff5db0486"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[targets]
test = ["Bench", "Statistics", "StructArrays"]
