# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.2"
manifest_format = "2.0"
project_hash = "321b03e9606f5eb76859f9e3d0caffe23495b471"

[[deps.Vehicle]]
path = "../Vehicle"
uuid = "457ea107-df29-4b41-9739-e753b442a278"
version = "1.0.0-DEV"
