name = "Calculator"
uuid = "e322ec89-91f6-413d-a70f-e5cf32ece82d"
authors = ["eeff <33566201+eeff@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
