name = "Assets"
uuid = "c67f7160-f7bc-4618-87af-53ac305aa1ad"
authors = ["eeff < 33566201+eeff@users.noreply.github.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
