name = "Global"
uuid = "11cc6d5e-1e1a-4e15-b271-543f9a52af55"
authors = ["eeff < 33566201+eeff@users.noreply.github.com>"]
version = "0.1.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[targets]
test = ["BenchmarkTools", "PrettyTables", "Printf"]
