name = "Global"
uuid = "11cc6d5e-1e1a-4e15-b271-543f9a52af55"
version = "0.1.0"
authors = ["eeff < 33566201+eeff@users.noreply.github.com>"]

[sources]
Bench = {path = "../Bench"}

[compat]
julia = "1.12"

[extras]
Bench = "517df1bc-ee24-4b58-84e4-955ff5db0486"

[targets]
test = ["Bench"]
